name: Translations syntaxis check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Run check
        run: node --experimental-modules --experimental-json-modules --unhandled-rejections=strict --es-module-specifier-resolution=node test.mjs
